# name: Audit code
# on: 
#   push:
#     branches: 
#       - master
# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v1
#     - name: Audit code
#       run: |
#         sudo apt install -y libpath-iterator-rule-perl libtest-perl-critic-perl 
#         curl -L https://raw.githubusercontent.com/htrgouvea/secureperl/main/secureperl.pl >> secureperl.pl && perl secureperl.pl